### ISSUE TITLE
Wifi reconnection problem

### ISSUE THREAD

**Issue by FaizanIjaz** [tripflex/captive-portal-wifi-stack#1]
Library works fine. However, there is a serious bug when connecting to a new ssid. If the already connected ssid is in range and the device is connected to it, wifi scan works. If the ssid is not in range that the device has credentials for, it gets stuck on scanning new wifi ssids in range.

**Comment by tripflex** [comment]
@FaizanIjaz what version of mos cli tool are you using?  So you're saying that if the device is attempting to connect to an existing network it has credentials for, but the SSID is not in range (meaning it can't connect), the scan will not work?

If this is the case, we may just need to call disconnect before calling scan, to make sure the device is not attempting to connect to existing SSID that may not be in range.

I'll try and do some testing on this myself today

**Comment by tripflex** [comment]
This may be related to this:
https://github.com/mongoose-os-libs/wifi/issues/18

**Comment by tripflex** [comment]
I submitted a PR to fix this issue, hopefully will be merged into lib soon:
https://github.com/mongoose-os-libs/wifi/pull/24/files

**Comment by FaizanIjaz** [comment]
Thanks! Meanwhile, if someone is looking for a reliable solution to configure WiFi credentials in ESP32, use the BLE method. More information can be found on the following link.
https://github.com/mongoose-os-libs/bt-service-config

**Comment by tripflex** [comment]
This has been included in lastest release of wifi lib now, closing this issue
