### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by janainascal** [tripflex/captive-portal-wifi-stack#4]
Hi, I love this library, it saved me so much time.

This isn't really a issue, but I need a custom web page for the portal.
I didn't find how to do it through your documentation. This is a feature that you plan to work?

Thanks for that beautiful stack 😄

**Comment by tripflex** [comment]
Look at the https://github.com/tripflex/captive-portal-wifi-web library that is used within this stack, you can customize the setting used to define the index file:
https://github.com/tripflex/captive-portal-wifi-web/blob/master/mos.yml#L12
