### ISSUE TITLE
Is this library abandoned? :( 

### ISSUE THREAD

**Issue by bbence84** [tripflex/captive-portal-wifi-stack#5]
I tried adding the library to my mos.xml, under libs:
  - origin: https://github.com/tripflex/captive-portal-wifi-stack
But even with only this included, I am getting build errors: https://pastebin.pl/view/raw/781491db

I would really need a captive portal solution for Mongoos OS, and I wanted to avoid having to write one from sratch. :(

Any suggestions?

Thanks!

**Comment by bbence84** [comment]
Manged to get it to work by adding the following to the config_schema in the mos_xml:

  - ["wifi.sta.protocol", "s", "xxx", {title: "Dummy config for ESP32 compatibility"}]

Maybe not the best solution, but it works. :)

**Comment by tripflex** [comment]
It's not abandoned, but yes i have not been adding any new features or anything, as this repo here is specifically just a "stack" that includes all the separate libraries ... so nothing on this library should or really will ever change, you should check the associated libraries linked in the readme for specific libraries
